### ISSUE TITLE
Babel plugin crashes with type object spread

### ISSUE THREAD

**Issue by edorivai** [codemix/flow-runtime#100]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

The babel plugin crashes if [type spreading](https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AzgSRWArsKAvFAN4BQUUAhgFxQo4C2ARhAE4A05UTtawrCFAHNOFAMa0AIpWARSAXwDcpUqEhQAYijiJUaQiS4A6EzuTosuYKO60A-HwHCbAE179BQhctIAzHChiuihQvkhIABRI8Gi0ZnqWeACUJPIq-oHB3JSsUTG0WvHoKcRpfuERxDRQAIzstlAA5GFIjfUSdBAA7lDSshFJ8knKLZXVdQ30ADZT7bQo3b0yEANDilAA9BtQEAAekEEQLipMOWO0EzxNLW1QHQs9fStJ9W7X4Y1rpKe5VRf1V2mszu80WTwGr1ozQ+a022xQSB2rFYSFYAEJvmc-rUAfMcDM5p1HstVsM4Tt9hBDi4kawgA) is used:

```js
type A = { a: any };
type B = { ...A, b: any };
```
    TypeError: /home/edo/test.js: Cannot read property 'name' of undefined
      
      at node_modules/babel-plugin-flow-runtime/lib/convert.js:664:40
      at Array.reduce (native)
      at converters.ObjectTypeAnnotation (node_modules/babel-plugin-flow-runtime/lib/convert.js:642:49)
      at convert (node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
      at converters.TypeAlias (node_modules/babel-plugin-flow-runtime/lib/convert.js:401:14)
      at convert (node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
      at TypeAlias (node_modules/babel-plugin-flow-runtime/lib/transformVisitors.js:165:47)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)

### What is the expected behaviour?

It should not crash. I guess it should support type spreading, as that is now supported by Flow.

### Which package versions are you using?

```
├─ babel-plugin-flow-runtime@0.10.0
├─ flow-runtime@0.10.0
├─ flow-bin@0.44.2
node: v7.9.0
```

**Comment by phpnode** [comment]
fixed in 0.11.1
