### ISSUE TITLE
Cannot redefine property: TypeContext

### ISSUE THREAD

**Issue by Mayank1791989** [codemix/flow-runtime#128]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] flow-runtime

---

### What is the current behaviour?

Issue when multiple flow-runtime present.
```javascript
Object.defineProperty(globalContext$2, name, {
       ^
TypeError: Cannot redefine property: TypeContext
    at Function.defineProperty (native)
    at defineProperty (some_path/node_modules/flow-runtime/dist/flow-runtime.js:9346:10)

// NOTE: above stack trace is from flow-runtime v0.12
```
I am using two libs in project which depends on different version of flow-runtime and whenever 2nd lib is loading its throwing the error.

### Which package versions are you using?

v0.12 and v0.13

**Comment by flodiebold** [comment]
I am also running into this problem, when trying to use flow-runtime with jest. When generating automatic mocks, jest loads modules with a fresh registry, which causes flow-runtime to be loaded multiple times.

**Comment by bradennapier** [comment]
I get this problem simply by trying to use hot reloading.  Turn off flow-runtime and all is well. :(  lots of issues it seems right now with this library which sucks cause it's an absolutely amazing concept and execution just missing a few critical things it seems which right now is making it fairly unusable. 

```
asyncComponent.js:186 TypeError: Cannot redefine property: props
    at Function.defineProperty (<anonymous>)
    at defineProxyProperty (http://localhost:1212/dist/bundle.js:38972:12)
    at http://localhost:1212/dist/bundle.js:39056:9
    at Array.forEach (native)
    at Object.update (http://localhost:1212/dist/bundle.js:39049:18)
    at Object.update (http://localhost:1212/dist/bundle.js:38826:45)
    at Object.register (http://localhost:1212/dist/bundle.js:38390:23)
    at http://localhost:1212/dist/6.bundle.js:428:24
    at Object../app/screens/Login/Login.js (http://localhost:1212/dist/6.bundle
```
