### ISSUE TITLE
Feature Request: $Reify<Type> (like in babel-plugin-tcomb)

### ISSUE THREAD

**Issue by jedwards1211** [codemix/flow-runtime#150]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

I'd like to be able to use `babel-plugin-flow-runtime` to *explicitly create a validator* from a flow type and *explicitly call it* to validate some JSON I've received from a client.

I don't want it to automatically perform runtime checking of my flow annotations, I only want to use it explicitly.

With `babel-plugin-tcomb` it's possible to explicitly create and use validators like so:

```js
/* @flow */

type Person = {
  firstName: string,
  lastName: string,
}

const checkPerson = (({}: any): $Reify<Person>)

checkPerson({firstName: 'Andy', lastName: 'Edwards'})
checkPerson({firstName: 'Someone'})
```
Output:

```
$ babel-node src/index.js
/Users/andy/babel-plugin-tcomb-test/node_modules/tcomb/lib/fail.js:2
  throw new TypeError('[tcomb] ' + message);
  ^

TypeError: [tcomb] Invalid value undefined supplied to Person/lastName: String
    at Function.fail (/Users/andy/babel-plugin-tcomb-test/node_modules/tcomb/lib/fail.js:2:9)
    at assert (/Users/andy/babel-plugin-tcomb-test/node_modules/tcomb/lib/assert.js:14:12)
    at Irreducible (/Users/andy/babel-plugin-tcomb-test/node_modules/tcomb/lib/irreducible.js:18:7)
    at create (/Users/andy/babel-plugin-tcomb-test/node_modules/tcomb/lib/create.js:9:104)
    at Interface (/Users/andy/babel-plugin-tcomb-test/node_modules/tcomb/lib/interface.js:70:22)
    at Object.<anonymous> (/Users/andy/babel-plugin-tcomb-test/src/index.js:11:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/andy/babel-plugin-tcomb-test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/andy/babel-plugin-tcomb-test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
```

**Comment by jedwards1211** [comment]
actually maybe this is already possible? https://github.com/codemix/flow-runtime/blob/master/packages/babel-plugin-flow-runtime/src/transformVisitors.js#L139

**Comment by jedwards1211** [comment]
Yeah, I see in the [Type Refinements](https://codemix.github.io/flow-runtime/#/docs/type-refinements) section of the docs that it's possible.  That wasn't a very obvious place to look.
