### ISSUE TITLE
Support React-Native

### ISSUE THREAD

**Issue by linonetwo** [codemix/flow-runtime#17]
When install for react-native, it will throws :

```
transformed 732/776 (94%)(node:12140) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 1362): 

SyntaxError: TransformError: xxxapp\node_modules\flow-runtime\flow-runtime.js: 
Couldn't find preset "env" relative to directory "xxxapp\\node_modules\\flow-runtime"
```

**Comment by linonetwo** [comment]
After manually install ```npm install babel-preset-env --save-dev```   

It throws ```Can't find variable: WeakSet```

After adding ```
var WeakSet = require('weakset');
require('core-js');
```

 It still throws ```babelHelpers.typeof is not a function```

I think this project should compile using ```react-native-stage-0/decorator-support``` to support both nodeJS side and react-native side.

**Comment by linonetwo** [comment]
Ok, try it tonight.

**Comment by linonetwo** [comment]
All my trying to use react-native related presets resulted in " Unsyntactic continue (530:0) "  

Seems https://github.com/codemix/flow-runtime/blob/master/packages/flow-runtime/src/registerBuiltins.js#L530 is the cause. Can you guess what's happening here?

**Comment by phpnode** [comment]
@linonetwo that's very strange, it's not hard to rewrite that code to avoid labels but I'd love to know why it's happening, what JS engine doesn't support them?

**Comment by linonetwo** [comment]
I guess It's react-native related presets' uglify that destroyed it. I've tried babel-preset-react-native and babel-preset-react-native-stage-0, resulting in the same thing.
  
After adding label manually there still being some problem, I'm working on them first

**Comment by linonetwo** [comment]
Just for reference, RN style babeled code:

```javascript
//loop:  <- striped
for(var _iterator10=input,_isArray10=Array.isArray(_iterator10),_i12=0,_iterator10=_isArray10?_iterator10:_iterator10[typeof Symbol==='function'?Symbol.iterator:'@@iterator']();;){var _ref16;if(_isArray10){if(_i12>=_iterator10.length)break;_ref16=_iterator10[_i12++];}else{_i12=_iterator10.next();if(_i12.done)break;_ref16=_i12.value;}var value=_ref16;
for(var i=0;i<valueTypes.length;i++){
var type=valueTypes[i];
if(type.accepts(value)){
continue loop;
}
}
valueTypes.push(t.typeOf(value));
}
```

web style 

```javascript
      try {
        loop: for (var _iterator10 = input[Symbol.iterator](), _step10; !(_iteratorNormalCompletion10 = (_step10 = _iterator10.next()).done); _iteratorNormalCompletion10 = true) {
          var value = _step10.value;

          for (var i = 0; i < valueTypes.length; i++) {
            var type = valueTypes[i];
            if (type.accepts(value)) {
              continue loop;
            }
          }
          valueTypes.push(t.typeOf(value));
        }
      }
```

**Comment by linonetwo** [comment]
Oh It's a little hard... Too late tonight, try it later...

**Comment by phpnode** [comment]
@linonetwo thanks for your help with this

**Comment by phpnode** [comment]
@linonetwo I'm curious whether or not this is fixed for you in v0.2.0?

**Comment by maraujop** [comment]
@phpnode  I've tried connecting flow-runtime with my React Native 0.39.2 project and packager fails to transform bundle, it hangs in react native `StatusBar`, not sure why.

So I'm guessing it doesn't support it yet.

**Comment by phpnode** [comment]
It looks like it may be related to this - https://github.com/tleunen/babel-plugin-module-resolver/issues/29

Does the solution from the last comment in that thread have any effect?

```
npm start -- --reset-cache
```

**Comment by computerjazz** [comment]
Also hung up on the StatusBar. Resetting the cache had no effect.

`/react-native/Libraries/Components/StatusBar/StatusBar.js: Property value expected type of string but got null`

**Comment by phpnode** [comment]
@computerjazz that sounds like it could be a legitimate type error

**Comment by DaleJefferson** [comment]
React Native 0.42 fails to transform with an error from UIManager.
```
TransformError: /Users/dale/Development/hydra/node_modules/react-native/Libraries/ReactNative/UIManager.js: /Users/dale/Development/hydra/node_modules/react-native/Libraries/ReactNative/UIManager.js: Property value expected type of string but got null

RCTFatal
-[RCTBatchedBridge stopLoadingWithError:]
__25-[RCTBatchedBridge start]_block_invoke_2
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

**Comment by ndbroadbent** [comment]
I don't know if this helps, but I wanted to get the stack trace of this error, so I changed `node_modules/babel-types/lib/index.js:156` to:

```js
function assertValueType(type) {
  function validate(node, key, val) {
    var valid = getType(val) === type;

    if (!valid) {
      const err = new TypeError("Property " + key + " expected type of " + type + " but got " + getType(val));

      console.log(err.stack)

      throw err
    }
  }

  validate.type = type;

  return validate;
}
```

So now the output from the React Native packager looks like this:


```js
Loading dependency graph, done.
Warning: The transform cache was reset.
Bundling `index.ios.js`
  Transforming modules  ▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░  13.0% (79/219)...TypeError: Property value expected type of string but got null
    at Object.validate (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/definitions/index.js:161:19)
    at validate (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/index.js:466:7)
    at converters.GenericTypeAnnotation (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:599:52)
    at convert (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at /Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:527:12
    at Array.map (native)
    at converters.UnionTypeAnnotation (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:526:33)
    at convert (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
Bundling `index.ios.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░  60.6% (334/429)...TypeError: Property value expected type of string but got null
    at Object.validate (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/definitions/index.js:161:19)
    at validate (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/index.js:466:7)
    at converters.GenericTypeAnnotation (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:599:52)
    at convert (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at converters.NullableTypeAnnotation (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:436:35)
    at convert (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at converters.FunctionTypeAnnotation (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:724:38)
    at convert (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
Bundling `index.ios.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░  91.5% (815/852)...TypeError: Property value expected type of string but got null
    at Object.validate (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/definitions/index.js:161:19)
    at validate (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/Users/ndbroadbent/code/my_app/node_modules/babel-types/lib/index.js:466:7)
    at converters.GenericTypeAnnotation (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:599:52)
    at convert (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at converters.TypeAnnotation (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:432:10)
    at convert (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at functionToArgs (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:819:82)
    at converters.Function (/Users/ndbroadbent/code/my_app/node_modules/babel-plugin-flow-runtime/lib/convert.js:893:14)
Bundling `index.ios.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░  96.3% (850/866)...
```


But I have no idea how to debug the code in `babel-plugin-flow-runtime/lib/convert.js`.

Also FYI, I changed the `.babelrc` in `babel-plugin-flow-runtime` and `flow-runtime` to use the ` `react-native-stage-0` preset.

I'm not sure if that was a good idea, but it was complaining about not being able to find the `stage-0` preset.

**Comment by ndbroadbent** [comment]
So the error is happening at line 599 in `babel-plugin-flow-runtime/lib/convert.js`:

```
return context.call.apply(context, ['ref', t.stringLiteral(name)].concat(_toConsumableArray(typeParameters)));
```

The error happens when you call `t.stringLiteral(name)`, because `name` is `undefined`. 

I wrapped that line in a `try...catch`:

```js
      try {
        return context.call.apply(context, ['ref', t.stringLiteral(name)].concat(_toConsumableArray(typeParameters)));
      } catch(err) {
        console.log("got error in convert.js")
        console.log(err)

        console.log("\n\n-----------------------------\n\n")
        console.log("\nname:", name)
        console.log("\n\ntypeParameters[0]:\n\n", typeParameters[0])

        throw err
      }
```

#### Output:

```
name: undefined


typeParameters[0]:

 { type: 'CallExpression',
  callee:
   { type: 'MemberExpression',
     object: { type: 'Identifier', name: 't' },
     property: { type: 'Identifier', name: 'any' },
     computed: false },
  arguments: [],
  loc:
   SourceLocation {
     start: Position { line: 47, column: 35 },
     end: Position { line: 47, column: 38 } } }
```


Line 47 in `UIManager.js`:

```
view ?: 'window' | React.Element<any> | number,
```

Columns 35 to 38: `<any>`.


Then I tried to investigate why `name` was undefined. `id.isQualifiedTypeIdentifier()` is true, so it is being set here:

```
if (id.isQualifiedTypeIdentifier()) {
    subject = qualifiedToMemberExpression(context, id);
    var outer = getMemberExpressionObject(subject);
    name = outer.name;
```

Output from `console.log(outer)`:

```
 { type: 'CallExpression',
  callee:
   { type: 'MemberExpression',
     object: { type: 'Identifier', name: 't' },
     property: { type: 'Identifier', name: 'get' },
     computed: false },
  arguments:
   [ Node {
       type: 'Identifier',
       start: 1551,
       end: 1556,
       loc: [Object],
       name: 'React' },
     { type: 'StringLiteral', value: 'Element' } ] }
```


Sorry, I think that's about as much as I can contribute. It would be awesome if `flow-runtime` could work with React Native!

**Comment by ndbroadbent** [comment]
I noticed that this error was happening for both `React.Element` and `Animated.Value`:

```
outer:

 { type: 'CallExpression',
  callee:
   { type: 'MemberExpression',
     object: { type: 'Identifier', name: 't' },
     property: { type: 'Identifier', name: 'get' },
     computed: false },
  arguments:
   [ Node {
       type: 'Identifier',
       start: 1798,
       end: 1806,
       loc: [Object],
       name: 'Animated' },
     { type: 'StringLiteral', value: 'Value' } ] }
```

So I got past that error with an ugly hack:

```js
    if (outer.type === 'CallExpression') {
      name = [outer.arguments[0].name, outer.arguments[1].value].join('.');
    } else {
      name = outer.name;
    }
```


Now I'm running into "Unable to resolve module ReactElementType". Exactly the same as this issue: https://github.com/facebook/react-native/issues/11492

(Interestingly, that issue is also happening with `flow-react-proptypes`, which is what I was trying to use before `flow-runtime`.)

It should be finding `ReactElementType` at `node_modules/react/lib/ReactElementType.js`, but the weird thing is that this is just an empty file:

```js
/**
 * Copyright 2016-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * 
 */

'use strict';
```

There's probably some magic going on here that I don't understand.

**Comment by SukantGujar** [comment]
The issue pointed by @ndbroadbent referenced [this one](https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/62), which has since been fixed and merged. Any chances of fixing this one?

**Comment by SukantGujar** [comment]
Maybe the react-native build doesn't bundle [ReactElementType](https://github.com/facebook/react/blob/master/src/shared/ReactElementType.js) definition.

**Comment by SukantGujar** [comment]
@phpnode noob question, would it be possible for a react-native flavor which ignores the types missing in the build, but works with user defined types? It will at least allow some usage of this library in RN. Thanks.

**Comment by skovhus** [comment]
Adding https://github.com/zloirock/core-js using `import 'core-js/es6'` works for me.

**Comment by liamondrop** [comment]
Confirmed, adding `import core-js/es6` to index.android.js seems to solve the compatibility issues with React Native Android. iOS doesn't appear to have any issues.

**Comment by linonetwo** [comment]
OK, seems this can be closed now!
