### ISSUE TITLE
Object key as type without identifier throws TypeError

### ISSUE THREAD

**Issue by seveibar** [codemix/flow-runtime#56]
This is a:

 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [X] babel-plugin-flow-runtime
 - [ ] flow-runtime-validatosr
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

```javascript
// input.js
type Animal = {};

type AnimalID = string

type AnimalMap = {
  [AnimalID]: Animal,
}
```

throws...
```bash
TypeError: src/types/test.js: Cannot read property 'name' of null
    at converters.ObjectTypeIndexer (/home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/convert.js:708:62)
    at convert (/home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at /home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/convert.js:682:12
    at Array.map (native)
    at converters.ObjectTypeAnnotation (/home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/convert.js:681:114)
    at convert (/home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at converters.TypeAlias (/home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/convert.js:400:14)
    at convert (/home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/convert.js:49:16)
    at TypeAlias (/home/seve/workspace/okcollege/libs/okc-js/node_modules/babel-plugin-flow-runtime/lib/transformVisitors.js:133:47)
    at NodePath._call (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:76:18)
```

---

### What is the expected behaviour?

Successful compilation.

---

### Which package versions are you using?

Approximately,
```javascript
"dependencies": {
    "babel-cli": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-plugin-flow-runtime": "^0.5.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.23.0",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-preset-stage-1": "^6.22.0"
  },
  "babel": {
    "presets": [
      "stage-1"
    ],
    "plugins": [
      [
        "transform-flow-strip-types"
      ],
      [
        "flow-runtime"
      ],
      [
        "transform-es2015-modules-commonjs"
      ]
    ]
  }
```

---

I've used this syntax for some time, but I don't see any official documentation saying it is supported- but it is working with flow right now so it may be worth supporting.

The workaround or "correct" syntax is as follows...
```javascript
// input.js
type Animal = {};

type AnimalID = string

type AnimalMap = {
  [id: AnimalID]: Animal,
}
```

**Comment by awestroke** [comment]
I have this problem, too. If I find the time I'll try to create a PR for this.

**Comment by awestroke** [comment]
Works fine now. Thank you @phpnode! Really appreciate the library
