### ISSUE TITLE
Runtime error when generator signature is any

### ISSUE THREAD

**Issue by dapetcu21** [codemix/flow-runtime#77]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

The following code fails at runtime:

```js
// Changing this from any to Generator<number, void, void> works
function* someGenerator (): any {
  yield 12;
  yield 42;
}

for (const it of someGenerator()) {
  console.log(it);
}
```

The error:

```
Uncaught ReferenceError: _yieldType is not defined
    at someGenerator$ (eval at <anonymous> (http://localhost:3000/bundle.js:3992:1), <anonymous>:46:18)
    at tryCatch (eval at <anonymous> (http://localhost:3000/bundle.js:9008:1), <anonymous>:64:40)
    at Generator.invoke [as _invoke] (eval at <anonymous> (http://localhost:3000/bundle.js:9008:1), <anonymous>:299:22)
    at Generator.prototype.(anonymous function) [as next] (eval at <anonymous> (http://localhost:3000/bundle.js:9008:1), <anonymous>:116:21)
    at eval (eval at <anonymous> (http://localhost:3000/bundle.js:3992:1), <anonymous>:67:116)
    at Object.<anonymous> (http://localhost:3000/bundle.js:3992:1)
    at __webpack_require__ (http://localhost:3000/bundle.js:660:30)
    at fn (http://localhost:3000/bundle.js:84:20)
    at Object.<anonymous> (http://localhost:3000/bundle.js:9081:18)
    at __webpack_require__ (http://localhost:3000/bundle.js:660:30)
```

---

### What is the expected behaviour?

It should run just fine, as it's valid Flow syntax.

---

### Which package versions are you using?

babel-plugin-flow-runtime@0.10.0

**Comment by phpnode** [comment]
fixed in 0.11.1
